LRCA-124 - Fixed validations removing data
last-rev-llc/contentful-ui-extensions pull request #98
Opened 2021-06-30 16:01 UTC by ajwhitley

Provider information was being removed if the json object was not valid.
Changed this to include the provider information when saving json input.
Also added validations to check json to make sure it has 2 properties, or mark invalid.

2021-06-30 16:24 UTC, camiloriosf requested changes

2021-06-30 16:24 UTC, camiloriosf commented on src/extensions/FormBuilder/hooks/useFormConfig.js
> +    console.log('loadState', { steps, provider });
let's remove this console.log

2021-06-30 16:24 UTC, camiloriosf commented on src/extensions/FormBuilder/hooks/useProviderConfig.js
> +      console.log({ newParameters, newType, values }) ||
let's remove this console.log

2021-06-30 16:28 UTC, camiloriosf approved these changes
LGTM

2021-07-01 16:01 UTC, maxtechera submitted a review, later dismissed
LGTM!

2022-06-29 14:12 UTC, camiloriosf approved these changes

2022-06-29 14:17 UTC, merged